extern unsigned long startTime;
extern unsigned long startTimeCounter;
extern unsigned int countdownTimer;
extern unsigned long sleepStartTime;
extern unsigned long adminRuntimer;
extern unsigned long runtimer;
extern bool runAllowed;
extern bool runstate;
extern int adminMax;
extern int adminUse;
extern int runCount;
extern int runCountTimer;
extern int runCountMaxTime;
extern unsigned long runCountStartTime;